### ISSUE TITLE
Development server throws an error on node 18

### ISSUE THREAD

**Issue by abrahamtara** [css-for-js/character-creator#39]
Hi, 

It seems like the development server for this project doesn't run on the latest LTS version of Node (18.15.0) -- the below error gets thrown. 
I've switched back to a previous Node version (16.14.2) and it runs fine on that. Possibly the version of `react-scripts` used by this repo needs to be upgraded to v5? ([source](https://stackoverflow.com/a/71334532))

```
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/taraabraham/Projects/css-course/character-creator/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/taraabraham/Projects/css-course/character-creator/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/taraabraham/Projects/css-course/character-creator/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/taraabraham/Projects/css-course/character-creator/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/taraabraham/Projects/css-course/character-creator/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/taraabraham/Projects/css-course/character-creator/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/taraabraham/Projects/css-course/character-creator/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/taraabraham/Projects/css-course/character-creator/node_modules/loader-runner/lib/LoaderRunner.js:221:10)

```

**Comment by abrahamtara** [comment]
Closing issue as I can see this is covered in the troubleshooting guide linked in the README
